#!/usr/bin/env node
// Builds training/catalog.json and training/CATALOG.md from every course.json that declares a track,
// plus the learning journeys in training/journeys.json (optional). --check fails on drift.
//
//   node training/lib/build-catalog.mjs [--check]
import { readFile, writeFile, readdir, stat } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const checkOnly = process.argv.includes('--check');
const TRACKS = [
  ['security-awareness', 'Security awareness', 'For everyone at the firm. Short modules and three-lesson courses on the habits that stop most incidents.'],
  ['ai-at-work', 'AI at work', 'For everyone who uses an AI assistant. Framing, context, checking, and not leaking.'],
  ['technology-operations', 'Technology operations', 'For the operator and the people in the room when something goes wrong.'],
];

function minutes(lessons) {
  return lessons.map((lesson) => lesson.duration.match(/^(\d+)–(\d+)/u)).reduce((sum, m) => [sum[0] + Number(m[1]), sum[1] + Number(m[2])], [0, 0]);
}

const entries = [];
for (const name of (await readdir(root)).sort()) {
  const dir = join(root, name);
  if (!(await stat(dir)).isDirectory()) continue;
  const raw = await readFile(join(dir, 'course.json'), 'utf8').catch(() => null);
  if (!raw) continue;
  const course = JSON.parse(raw);
  const track = course.track ?? (course.slug === 'ai-at-work' ? 'ai-at-work' : undefined);
  if (!track) continue;
  const [min, max] = minutes(course.lessons);
  entries.push({
    slug: course.slug, title: course.title, track, format: course.format ?? 'course',
    audience: course.audience ?? 'Employees across administration, finance, marketing, HR, project teams, and other everyday roles.',
    prerequisites: course.prerequisites ?? [], description: course.description, reviewedOn: course.reviewedOn,
    lessons: course.lessons.map((lesson) => ({ number: lesson.number, title: lesson.title, duration: lesson.duration })),
    minutes: { min, max }, path: `${course.slug}/README.md`,
  });
}
if (entries.length === 0) throw new Error('No courses found');

const journeysRaw = await readFile(join(root, 'journeys.json'), 'utf8').catch(() => null);
const journeys = journeysRaw ? JSON.parse(journeysRaw) : [];
const bySlug = new Map(entries.map((entry) => [entry.slug, entry]));
for (const journey of journeys) {
  for (const key of ['id', 'title', 'audience', 'description']) if (typeof journey[key] !== 'string' || !journey[key]) throw new Error(`journey ${journey.id ?? '?'}: missing ${key}`);
  if (!Array.isArray(journey.steps) || journey.steps.length < 2) throw new Error(`journey ${journey.id}: expected at least two steps`);
  for (const slug of journey.steps) if (!bySlug.has(slug)) throw new Error(`journey ${journey.id}: unknown course ${slug}`);
}

const catalog = { generatedFrom: 'training/*/course.json', tracks: TRACKS.map(([id, title, description]) => ({ id, title, description })), courses: entries, journeys };
const json = JSON.stringify(catalog, null, 2) + '\n';

const time = (entry) => `${entry.minutes.min}–${entry.minutes.max} min`;
const row = (entry) => `| [${entry.title}](${entry.path}) | ${entry.format === 'bite' ? 'Short module' : 'Course'} | ${entry.audience} | ${entry.lessons.length} | ${time(entry)} | ${entry.reviewedOn} |`;
const table = (rows) => `| Module | Format | For | Lessons | Time | Sources reviewed |\n| --- | --- | --- | --- | --- | --- |\n${rows.join('\n')}`;
const journeyBlock = (journey) => {
  const steps = journey.steps.map((slug) => bySlug.get(slug));
  const total = steps.reduce((sum, entry) => [sum[0] + entry.minutes.min, sum[1] + entry.minutes.max], [0, 0]);
  return `### ${journey.title}\n\n${journey.description}\n\n**For:** ${journey.audience} · **Total time:** ${total[0]}–${total[1]} minutes\n\n${steps.map((entry, index) => `${index + 1}. [${entry.title}](${entry.path}) (${time(entry)})`).join('\n')}`;
};
const md = `<!-- Generated by training/lib/build-catalog.mjs from every course.json. Edit the courses or journeys.json and regenerate. -->

# Training catalog

${entries.length} modules across three tracks: ${entries.filter((entry) => entry.format === 'bite').length} short modules of one or two lessons, and ${entries.filter((entry) => entry.format !== 'bite').length} courses of three lessons or more. Every module works on paper or in a document, uses a fictional packet, and needs no tool account. Suggested times are starting estimates.

Filter by track below, or start from a [learning journey](#learning-journeys). Facilitators: each module has its own facilitator guide and worksheet.

${TRACKS.map(([id, title, description]) => `## ${title}\n\n${description}\n\n${table(entries.filter((entry) => entry.track === id).map(row))}`).join('\n\n')}

## Learning journeys

${journeys.length ? journeys.map(journeyBlock).join('\n\n') : 'No journeys defined yet.'}

## How to use this catalog

- **Onboarding:** assign the "everyone" journey in the first month, one module a week.
- **Refreshers:** a short module takes less than fifteen minutes; rotate one a month.
- **After an incident or a near miss:** run the closest module as a session using its facilitator guide, then the relevant tabletop.
- **Records:** keep completion evidence in your own training record, not in this repository. Every module says plainly that its answer keys are authored comparisons, not assessments of the reader.

Maintain: edit a course's \`course.json\`, run its builder, then \`node training/lib/build-catalog.mjs\`. CI checks both.
`;

const outputs = new Map([[join(root, 'catalog.json'), json], [join(root, 'CATALOG.md'), md]]);
const stale = [];
for (const [location, expected] of outputs) {
  if (checkOnly) {
    const actual = await readFile(location, 'utf8').catch(() => null);
    if (actual !== expected) stale.push(location);
  } else {
    await writeFile(location, expected, 'utf8');
  }
}
if (stale.length) throw new Error(`Catalog drift: ${stale.map((p) => p.replace(root + '/', '')).join(', ')}. Run build-catalog.mjs.`);
console.log(`Catalog: ${entries.length} modules, ${journeys.length} journeys ${checkOnly ? 'checked' : 'generated'}.`);
